# Generated by Django 5.2.4 on 2025-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_date", models.DateField()),
                ("supplier_name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=10)),
                ("bill_no", models.CharField(max_length=50)),
                ("invoice_no", models.CharField(max_length=50)),
                ("bill_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("tds_rate", models.DecimalField(decimal_places=2, max_digits=2)),
                ("tds_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("vds_rate", models.DecimalField(decimal_places=2, max_digits=2)),
                ("vds_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("net_payment", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Signed", "Signed"),
                            ("Received", "Received"),
                        ],
                        default="Received",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("remarks", models.TextField()),
            ],
        ),
    ]
