# Generated by Django 5.2.4 on 2025-11-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bill", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="tds_value",
            new_name="tds",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="vds_value",
            new_name="vds",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="tds_rate",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="vds_rate",
        ),
    ]
