# Generated by Django 5.2.8 on 2025-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_rename_tds_value_bill_tds_rename_vds_value_bill_vds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-status']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='unit',
            field=models.CharField(choices=[('Flour Mill', 'Flour Mill'), ('Drinking Water', 'Drinking Water'), ('FM & DW', 'FM & DW')], max_length=20),
        ),
    ]
